<?xml version='1.0' encoding='utf-8'?>
<!--
	conjugation-es.xml - List of Spanish conjugation templates.
	The templates were generated by SekouD using Unsupervised Learning,
	and follow the xml schema defined by Pierre Sarrazin in verbiste.
	Further improved by Brett Tolbert:
	Removed uncessary compound tenses, as they can be conjugated with 
	only the helping verb and participle. Also cleaned up the DTD and 
	fixed a lot of errors in the templates.

	Coypright (C) 2019 Brett Tolbert <https://github.com/bretttolbert/verbecc>
	Copyright (C) 2018 SekouD <https://github.com/SekouD>
	Copyright (C) 2010 Pierre Sarrazin <http://sarrazip.com/>

	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	You should have received a copy of the GNU General Public License
	along with this program; if not, write to the Free Software
	Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
	02110-1301, USA.
-->
<!DOCTYPE conjugation-es [
<!ELEMENT conjugation-es (template)+>
<!ATTLIST conjugation-es xmlns CDATA #FIXED "">
<!ELEMENT template (indicativo , subjuntivo , imperativo , (condicional , infinitivo , gerundio , participo)?)>
<!ATTLIST template xmlns CDATA #FIXED "">
<!ATTLIST template name NMTOKEN #REQUIRED>
<!ELEMENT indicativo (presente , pretérito-imperfecto , pretérito-perfecto-simple , futuro)?>
<!ATTLIST indicativo xmlns CDATA #FIXED "">
<!ELEMENT subjuntivo (presente , pretérito-imperfecto-1 , pretérito-imperfecto-2 , futuro)?>
<!ATTLIST subjuntivo xmlns CDATA #FIXED "">
<!ELEMENT imperativo (imperativo-afirmativo , imperativo-non)>
<!ATTLIST imperativo xmlns CDATA #FIXED "">
<!ELEMENT condicional (condicional-present)>
<!ATTLIST condicional xmlns CDATA #FIXED "">
<!ELEMENT infinitivo (infinitivo-infinitivo)>
<!ATTLIST infinitivo xmlns CDATA #FIXED "">
<!ELEMENT gerundio (gerundio-gerondio)>
<!ATTLIST gerundio xmlns CDATA #FIXED "">
<!ELEMENT participo (participo-participo)>
<!ATTLIST participo xmlns CDATA #FIXED "">
<!ELEMENT presente (p)+>
<!ATTLIST presente xmlns CDATA #FIXED "">
<!ELEMENT pretérito-imperfecto (p)+>
<!ATTLIST pretérito-imperfecto xmlns CDATA #FIXED "">
<!ELEMENT pretérito-perfecto-simple (p)+>
<!ATTLIST pretérito-perfecto-simple xmlns CDATA #FIXED "">
<!ELEMENT futuro (p)+>
<!ATTLIST futuro xmlns CDATA #FIXED "">
<!ELEMENT presente (p)+>
<!ATTLIST presente xmlns CDATA #FIXED "">
<!ELEMENT pretérito-imperfecto-1 (p)+>
<!ATTLIST pretérito-imperfecto-1 xmlns CDATA #FIXED "">
<!ELEMENT pretérito-imperfecto-2 (p)+>
<!ATTLIST pretérito-imperfecto-2 xmlns CDATA #FIXED "">
<!ELEMENT futuro (p)+>
<!ATTLIST futuro xmlns CDATA #FIXED "">
<!ELEMENT imperativo-afirmativo (p)+>
<!ATTLIST imperativo-afirmativo xmlns CDATA #FIXED "">
<!ELEMENT imperativo-non (p)+>
<!ATTLIST imperativo-non xmlns CDATA #FIXED "">
<!ELEMENT condicional-present (p)+>
<!ATTLIST condicional-present xmlns CDATA #FIXED "">
<!ELEMENT infinitivo-infinitivo (p)+>
<!ATTLIST infinitivo-infinitivo xmlns CDATA #FIXED "">
<!ELEMENT gerundio-gerondio (p)+>
<!ATTLIST gerundio-gerondio xmlns CDATA #FIXED "">
<!ELEMENT participo-participo (p)>
<!ATTLIST participo-participo xmlns CDATA #FIXED "">
<!ELEMENT p (i)+>
<!ATTLIST p xmlns CDATA #FIXED "">
<!ELEMENT i (#PCDATA)>
<!ATTLIST i xmlns CDATA #FIXED "">
]>
<conjugation-es>

<template name="abol:ir">
	<indicativo>
		<presente>
			<p><i>o</i></p>
			<p><i>es</i><i>ís</i></p>
			<p><i>e</i></p>
			<p><i>imos</i></p>
			<p><i>ís</i></p>
			<p><i>en</i></p>
		</presente>
		<pretérito-imperfecto>
			<p><i>ía</i></p>
			<p><i>ías</i></p>
			<p><i>ía</i></p>
			<p><i>íamos</i></p>
			<p><i>íais</i></p>
			<p><i>ían</i></p>
		</pretérito-imperfecto>
		<pretérito-perfecto-simple>
			<p><i>ía</i></p>
			<p><i>ías</i></p>
			<p><i>ía</i></p>
			<p><i>íamos</i></p>
			<p><i>íais</i></p>
			<p><i>ían</i></p>
		</pretérito-perfecto-simple>
		<futuro>
			<p><i>iré</i></p>
			<p><i>irás</i></p>
			<p><i>irrá</i></p>
			<p><i>iremos</i></p>
			<p><i>iréis</i></p>
			<p><i>irán</i></p>
		</futuro>
		</indicativo>
	<subjuntivo>
	</subjuntivo>
	<imperativo>
		<imperativo-afirmativo>
			<p><i/></p>
			<p><i/></p>
			<p><i>iendo</i></p>
			<p><i/></p>
			<p><i/></p>
		</imperativo-afirmativo>
		<imperativo-non>
			<p><i>ir</i></p>
			<p><i/></p>
			<p><i/></p>
			<p><i>ido</i></p>
			<p><i/></p>
		</imperativo-non>
	</imperativo>
	<condicional>
		<condicional-present>
			<p><i>iría</i></p>
			<p><i>irías</i></p>
			<p><i>iría</i></p>
			<p><i>iríamos</i></p>
			<p><i>iríais</i></p>
			<p><i>irían</i></p>
		</condicional-present>
		</condicional>
	<infinitivo>
		<infinitivo-infinitivo>
			<p><i>ir</i></p>
			<p><i>ir</i></p>
		</infinitivo-infinitivo>
	</infinitivo>
	<gerundio>
		<gerundio-gerondio>
			<p><i>iendo</i></p>
			<p><i>iendo</i></p>
		</gerundio-gerondio>
	</gerundio>
	<participo>
		<participo-participo>
			<p><i>ido</i></p>
		</participo-participo>
	</participo>
</template>

<template name="act:uar">
	<indicativo>
		<presente>
			<p><i>úo</i></p>
			<p><i>úas</i></p>
			<p><i>úa</i></p>
			<p><i>uamos</i></p>
			<p><i>uáis</i></p>
			<p><i>úan</i></p>
		</presente>
		<pretérito-imperfecto>
			<p><i>uaba</i></p>
			<p><i>uabas</i></p>
			<p><i>uaba</i></p>
			<p><i>uábamos</i></p>
			<p><i>uabais</i></p>
			<p><i>uaban</i></p>
		</pretérito-imperfecto>
		<pretérito-perfecto-simple>
			<p><i>ué</i></p>
			<p><i>uaste</i></p>
			<p><i>uó</i></p>
			<p><i>uamos</i></p>
			<p><i>uasteis</i></p>
			<p><i>uaron</i></p>
		</pretérito-perfecto-simple>
		<futuro>
			<p><i>uaré</i></p>
			<p><i>uarás</i></p>
			<p><i>uará</i></p>
			<p><i>uaremos</i></p>
			<p><i>uaréis</i></p>
			<p><i>uarán</i></p>
		</futuro>
		</indicativo>
	<subjuntivo>
		<presente>
			<p><i>úe</i></p>
			<p><i>úes</i></p>
			<p><i>úe</i></p>
			<p><i>uemos</i></p>
			<p><i>uéis</i></p>
			<p><i>úen</i></p>
		</presente>
		<pretérito-imperfecto-1>
			<p><i>uara</i></p>
			<p><i>uaras</i></p>
			<p><i>uara</i></p>
			<p><i>uáramos</i></p>
			<p><i>uarais</i></p>
			<p><i>uaran</i></p>
		</pretérito-imperfecto-1>
		<pretérito-imperfecto-2>
			<p><i>uase</i></p>
			<p><i>uases</i></p>
			<p><i>uase</i></p>
			<p><i>uásemos</i></p>
			<p><i>uaseis</i></p>
			<p><i>uasen</i></p>
		</pretérito-imperfecto-2>
		<futuro>
			<p><i>uare</i></p>
			<p><i>uares</i></p>
			<p><i>uare</i></p>
			<p><i>uáremos</i></p>
			<p><i>uareis</i></p>
			<p><i>uaren</i></p>
		</futuro>
		</subjuntivo>
	<imperativo>
		<imperativo-afirmativo>
			<p><i>úa</i></p>
			<p><i>úe</i></p>
			<p><i>uemos</i></p>
			<p><i>uad</i></p>
			<p><i>úen</i></p>
		</imperativo-afirmativo>
		<imperativo-non>
			<p><i>úes</i></p>
			<p><i>úe</i></p>
			<p><i>uemos</i></p>
			<p><i>uéis</i></p>
			<p><i>úen</i></p>
		</imperativo-non>
	</imperativo>
	<condicional>
		<condicional-present>
			<p><i>uaría</i></p>
			<p><i>uarías</i></p>
			<p><i>uaría</i></p>
			<p><i>uaríamos</i></p>
			<p><i>uaríais</i></p>
			<p><i>uarían</i></p>
		</condicional-present>
		</condicional>
	<infinitivo>
		<infinitivo-infinitivo>
			<p><i>uar</i></p>
			<p><i>uado</i></p>
		</infinitivo-infinitivo>
	</infinitivo>
	<gerundio>
		<gerundio-gerondio>
			<p><i>uando</i></p>
			<p><i>uado</i></p>
		</gerundio-gerondio>
	</gerundio>
	<participo>
		<participo-participo>
			<p><i>uado</i></p>
		</participo-participo>
	</participo>
</template>

<template name="adqui:rir">
	<indicativo>
		<presente>
			<p><i>ero</i></p>
			<p><i>eres</i></p>
			<p><i>ere</i></p>
			<p><i>rimos</i></p>
			<p><i>rís</i></p>
			<p><i>eren</i></p>
		</presente>
		<pretérito-imperfecto>
			<p><i>ría</i></p>
			<p><i>rías</i></p>
			<p><i>ría</i></p>
			<p><i>ríamos</i></p>
			<p><i>ríais</i></p>
			<p><i>rían</i></p>
		</pretérito-imperfecto>
		<pretérito-perfecto-simple>
			<p><i>rí</i></p>
			<p><i>riste</i></p>
			<p><i>rió</i></p>
			<p><i>rimos</i></p>
			<p><i>risteis</i></p>
			<p><i>rieron</i></p>
		</pretérito-perfecto-simple>
		<futuro>
			<p><i>riré</i></p>
			<p><i>rirás</i></p>
			<p><i>rirá</i></p>
			<p><i>riremos</i></p>
			<p><i>riréis</i></p>
			<p><i>rirán</i></p>
		</futuro>
		</indicativo>
	<subjuntivo>
		<presente>
			<p><i>era</i></p>
			<p><i>eras</i></p>
			<p><i>era</i></p>
			<p><i>ramos</i></p>
			<p><i>ráis</i></p>
			<p><i>eran</i></p>
		</presente>
		<pretérito-imperfecto-1>
			<p><i>riera</i></p>
			<p><i>rieras</i></p>
			<p><i>riera</i></p>
			<p><i>riéramos</i></p>
			<p><i>rierais</i></p>
			<p><i>rieran</i></p>
		</pretérito-imperfecto-1>
		<pretérito-imperfecto-2>
			<p><i>riese</i></p>
			<p><i>rieses</i></p>
			<p><i>riese</i></p>
			<p><i>riésemos</i></p>
			<p><i>rieseis</i></p>
			<p><i>riesen</i></p>
		</pretérito-imperfecto-2>
		<futuro>
			<p><i>riere</i></p>
			<p><i>rieres</i></p>
			<p><i>riere</i></p>
			<p><i>riéremos</i></p>
			<p><i>riereis</i></p>
			<p><i>rieren</i></p>
		</futuro>
		</subjuntivo>
	<imperativo>
		<imperativo-afirmativo>
			<p><i>ere</i></p>
			<p><i>era</i></p>
			<p><i>ramos</i></p>
			<p><i>rid</i></p>
			<p><i>eran</i></p>
		</imperativo-afirmativo>
		<imperativo-non>
			<p><i>eras</i></p>
			<p><i>era</i></p>
			<p><i>ramos</i></p>
			<p><i>ráis</i></p>
			<p><i>eran</i></p>
		</imperativo-non>
	</imperativo>
	<condicional>
		<condicional-present>
			<p><i>riría</i></p>
			<p><i>rirías</i></p>
			<p><i>riría</i></p>
			<p><i>riríamos</i></p>
			<p><i>riríais</i></p>
			<p><i>rirían</i></p>
		</condicional-present>
		</condicional>
	<infinitivo>
		<infinitivo-infinitivo>
			<p><i>rir</i></p>
			<p><i>rido</i></p>
		</infinitivo-infinitivo>
	</infinitivo>
	<gerundio>
		<gerundio-gerondio>
			<p><i>riendo</i></p>
			<p><i>rido</i></p>
		</gerundio-gerondio>
	</gerundio>
	<participo>
		<participo-participo>
			<p><i>rido</i></p>
		</participo-participo>
	</participo>
</template>

<template name="ah:incar">
	<indicativo>
		<presente>
			<p><i>ínco</i></p>
			<p><i>íncas</i></p>
			<p><i>ínca</i></p>
			<p><i>incamos</i></p>
			<p><i>incáis</i></p>
			<p><i>íncan</i></p>
		</presente>
		<pretérito-imperfecto>
			<p><i>incaba</i></p>
			<p><i>incabas</i></p>
			<p><i>incaba</i></p>
			<p><i>incábamos</i></p>
			<p><i>incabais</i></p>
			<p><i>incaban</i></p>
		</pretérito-imperfecto>
		<pretérito-perfecto-simple>
			<p><i>inqué</i></p>
			<p><i>incaste</i></p>
			<p><i>incó</i></p>
			<p><i>incamos</i></p>
			<p><i>incasteis</i></p>
			<p><i>incaron</i></p>
		</pretérito-perfecto-simple>
		<futuro>
			<p><i>incaré</i></p>
			<p><i>incarás</i></p>
			<p><i>incará</i></p>
			<p><i>incaremos</i></p>
			<p><i>incaréis</i></p>
			<p><i>incarán</i></p>
		</futuro>
		</indicativo>
	<subjuntivo>
		<presente>
			<p><i>ínque</i></p>
			<p><i>ínques</i></p>
			<p><i>ínque</i></p>
			<p><i>inquemos</i></p>
			<p><i>inquéis</i></p>
			<p><i>ínquen</i></p>
		</presente>
		<pretérito-imperfecto-1>
			<p><i>incara</i></p>
			<p><i>incaras</i></p>
			<p><i>incara</i></p>
			<p><i>incáramos</i></p>
			<p><i>incarais</i></p>
			<p><i>incaran</i></p>
		</pretérito-imperfecto-1>
		<pretérito-imperfecto-2>
			<p><i>incase</i></p>
			<p><i>incases</i></p>
			<p><i>incase</i></p>
			<p><i>incásemos</i></p>
			<p><i>incaseis</i></p>
			<p><i>incasen</i></p>
		</pretérito-imperfecto-2>
		<futuro>
			<p><i>incare</i></p>
			<p><i>incares</i></p>
			<p><i>incare</i></p>
			<p><i>incáremos</i></p>
			<p><i>incareis</i></p>
			<p><i>incaren</i></p>
		</futuro>
		</subjuntivo>
	<imperativo>
		<imperativo-afirmativo>
			<p><i>ínca</i></p>
			<p><i>ínque</i></p>
			<p><i>inquemos</i></p>
			<p><i>incad</i></p>
			<p><i>ínquen</i></p>
		</imperativo-afirmativo>
		<imperativo-non>
			<p><i>ínques</i></p>
			<p><i>ínque</i></p>
			<p><i>inquemos</i></p>
			<p><i>inquéis</i></p>
			<p><i>ínquen</i></p>
		</imperativo-non>
	</imperativo>
	<condicional>
		<condicional-present>
			<p><i>incaría</i></p>
			<p><i>incarías</i></p>
			<p><i>incaría</i></p>
			<p><i>incaríamos</i></p>
			<p><i>incaríais</i></p>
			<p><i>incarían</i></p>
		</condicional-present>
		</condicional>
	<infinitivo>
		<infinitivo-infinitivo>
			<p><i>incar</i></p>
			<p><i>incado</i></p>
		</infinitivo-infinitivo>
	</infinitivo>
	<gerundio>
		<gerundio-gerondio>
			<p><i>incando</i></p>
			<p><i>incado</i></p>
		</gerundio-gerondio>
	</gerundio>
	<participo>
		<participo-participo>
			<p><i>incado</i></p>
		</participo-participo>
	</participo>
</template>

<template name="a:irar">
	<indicativo>
		<presente>
			<p><i>íro</i></p>
			<p><i>íras</i></p>
			<p><i>íra</i></p>
			<p><i>iramos</i></p>
			<p><i>iráis</i></p>
			<p><i>íran</i></p>
		</presente>
		<pretérito-imperfecto>
			<p><i>iraba</i></p>
			<p><i>irabas</i></p>
			<p><i>iraba</i></p>
			<p><i>irábamos</i></p>
			<p><i>irabais</i></p>
			<p><i>iraban</i></p>
		</pretérito-imperfecto>
		<pretérito-perfecto-simple>
			<p><i>iré</i></p>
			<p><i>iraste</i></p>
			<p><i>iró</i></p>
			<p><i>iramos</i></p>
			<p><i>irasteis</i></p>
			<p><i>iraron</i></p>
		</pretérito-perfecto-simple>
		<futuro>
			<p><i>iraré</i></p>
			<p><i>irarás</i></p>
			<p><i>irará</i></p>
			<p><i>iraremos</i></p>
			<p><i>iraréis</i></p>
			<p><i>irarán</i></p>
		</futuro>
		</indicativo>
	<subjuntivo>
		<presente>
			<p><i>íre</i></p>
			<p><i>íres</i></p>
			<p><i>íre</i></p>
			<p><i>iremos</i></p>
			<p><i>iréis</i></p>
			<p><i>íren</i></p>
		</presente>
		<pretérito-imperfecto-1>
			<p><i>irara</i></p>
			<p><i>iraras</i></p>
			<p><i>irara</i></p>
			<p><i>iráramos</i></p>
			<p><i>irarais</i></p>
			<p><i>iraran</i></p>
		</pretérito-imperfecto-1>
		<pretérito-imperfecto-2>
			<p><i>irase</i></p>
			<p><i>irases</i></p>
			<p><i>irase</i></p>
			<p><i>irásemos</i></p>
			<p><i>iraseis</i></p>
			<p><i>irasen</i></p>
		</pretérito-imperfecto-2>
		<futuro>
			<p><i>irare</i></p>
			<p><i>irares</i></p>
			<p><i>irare</i></p>
			<p><i>iráremos</i></p>
			<p><i>irareis</i></p>
			<p><i>iraren</i></p>
		</futuro>
		</subjuntivo>
	<imperativo>
		<imperativo-afirmativo>
			<p><i>íra</i></p>
			<p><i>íre</i></p>
			<p><i>iremos</i></p>
			<p><i>irad</i></p>
			<p><i>íren</i></p>
		</imperativo-afirmativo>
		<imperativo-non>
			<p><i>íres</i></p>
			<p><i>íre</i></p>
			<p><i>iremos</i></p>
			<p><i>iréis</i></p>
			<p><i>íren</i></p>
		</imperativo-non>
	</imperativo>
	<condicional>
		<condicional-present>
			<p><i>iraría</i></p>
			<p><i>irarías</i></p>
			<p><i>iraría</i></p>
			<p><i>iraríamos</i></p>
			<p><i>iraríais</i></p>
			<p><i>irarían</i></p>
		</condicional-present>
		</condicional>
	<infinitivo>
		<infinitivo-infinitivo>
			<p><i>irar</i></p>
			<p><i>irado</i></p>
		</infinitivo-infinitivo>
	</infinitivo>
	<gerundio>
		<gerundio-gerondio>
			<p><i>irando</i></p>
			<p><i>irado</i></p>
		</gerundio-gerondio>
	</gerundio>
	<participo>
		<participo-participo>
			<p><i>irado</i></p>
		</participo-participo>
	</participo>
</template>

<template name="and:ar">
	<indicativo>
		<presente>
			<p><i>o</i></p>
			<p><i>as</i></p>
			<p><i>a</i></p>
			<p><i>amos</i></p>
			<p><i>áis</i></p>
			<p><i>an</i></p>
		</presente>
		<pretérito-imperfecto>
			<p><i>aba</i></p>
			<p><i>abas</i></p>
			<p><i>aba</i></p>
			<p><i>ábamos</i></p>
			<p><i>abais</i></p>
			<p><i>aban</i></p>
		</pretérito-imperfecto>
		<pretérito-perfecto-simple>
			<p><i>uve</i></p>
			<p><i>uviste</i></p>
			<p><i>uvo</i></p>
			<p><i>uvimos</i></p>
			<p><i>uvisteis</i></p>
			<p><i>uvieron</i></p>
		</pretérito-perfecto-simple>
		<futuro>
			<p><i>aré</i></p>
			<p><i>arás</i></p>
			<p><i>ará</i></p>
			<p><i>aremos</i></p>
			<p><i>aréis</i></p>
			<p><i>arán</i></p>
		</futuro>
		</indicativo>
	<subjuntivo>
		<presente>
			<p><i>e</i></p>
			<p><i>es</i></p>
			<p><i>e</i></p>
			<p><i>emos</i></p>
			<p><i>éis</i></p>
			<p><i>en</i></p>
		</presente>
		<pretérito-imperfecto-1>
			<p><i>uviera</i></p>
			<p><i>uvieras</i></p>
			<p><i>uviera</i></p>
			<p><i>uviéramos</i></p>
			<p><i>uvierais</i></p>
			<p><i>uvieran</i></p>
		</pretérito-imperfecto-1>
		<pretérito-imperfecto-2>
			<p><i>uviese</i></p>
			<p><i>uvieses</i></p>
			<p><i>uviese</i></p>
			<p><i>uviésemos</i></p>
			<p><i>uvieseis</i></p>
			<p><i>uviesen</i></p>
		</pretérito-imperfecto-2>
		<futuro>
			<p><i>uviere</i></p>
			<p><i>uvieres</i></p>
			<p><i>uviere</i></p>
			<p><i>uviéremos</i></p>
			<p><i>uviereis</i></p>
			<p><i>uvieren</i></p>
		</futuro>
		</subjuntivo>
	<imperativo>
		<imperativo-afirmativo>
			<p><i>a</i></p>
			<p><i>e</i></p>
			<p><i>emos</i></p>
			<p><i>ad</i></p>
			<p><i>en</i></p>
		</imperativo-afirmativo>
		<imperativo-non>
			<p><i>es</i></p>
			<p><i>e</i></p>
			<p><i>emos</i></p>
			<p><i>éis</i></p>
			<p><i>en</i></p>
		</imperativo-non>
	</imperativo>
	<condicional>
		<condicional-present>
			<p><i>aría</i></p>
			<p><i>arías</i></p>
			<p><i>aría</i></p>
			<p><i>aríamos</i></p>
			<p><i>aríais</i></p>
			<p><i>arían</i></p>
		</condicional-present>
		</condicional>
	<infinitivo>
		<infinitivo-infinitivo>
			<p><i>ar</i></p>
			<p><i>ado</i></p>
		</infinitivo-infinitivo>
	</infinitivo>
	<gerundio>
		<gerundio-gerondio>
			<p><i>ando</i></p>
			<p><i>ado</i></p>
		</gerundio-gerondio>
	</gerundio>
	<participo>
		<participo-participo>
			<p><i>ado</i></p>
		</participo-participo>
	</participo>
</template>

<template name="as:ir">
	<indicativo>
		<presente>
			<p><i>go</i></p>
			<p><i>es</i></p>
			<p><i>e</i></p>
			<p><i>imos</i></p>
			<p><i>ís</i></p>
			<p><i>en</i></p>
		</presente>
		<pretérito-imperfecto>
			<p><i>ía</i></p>
			<p><i>ías</i></p>
			<p><i>ía</i></p>
			<p><i>íamos</i></p>
			<p><i>íais</i></p>
			<p><i>ían</i></p>
		</pretérito-imperfecto>
		<pretérito-perfecto-simple>
			<p><i>í</i></p>
			<p><i>iste</i></p>
			<p><i>ió</i></p>
			<p><i>imos</i></p>
			<p><i>isteis</i></p>
			<p><i>ieron</i></p>
		</pretérito-perfecto-simple>
		<futuro>
			<p><i>iré</i></p>
			<p><i>irás</i></p>
			<p><i>irá</i></p>
			<p><i>iremos</i></p>
			<p><i>iréis</i></p>
			<p><i>irán</i></p>
		</futuro>
		</indicativo>
	<subjuntivo>
		<presente>
			<p><i>ga</i></p>
			<p><i>gas</i></p>
			<p><i>ga</i></p>
			<p><i>gamos</i></p>
			<p><i>gáis</i></p>
			<p><i>gan</i></p>
		</presente>
		<pretérito-imperfecto-1>
			<p><i>iera</i></p>
			<p><i>ieras</i></p>
			<p><i>iera</i></p>
			<p><i>iéramos</i></p>
			<p><i>ierais</i></p>
			<p><i>ieran</i></p>
		</pretérito-imperfecto-1>
		<pretérito-imperfecto-2>
			<p><i>iese</i></p>
			<p><i>ieses</i></p>
			<p><i>iese</i></p>
			<p><i>iésemos</i></p>
			<p><i>ieseis</i></p>
			<p><i>iesen</i></p>
		</pretérito-imperfecto-2>
		<futuro>
			<p><i>iere</i></p>
			<p><i>ieres</i></p>
			<p><i>iere</i></p>
			<p><i>iéremos</i></p>
			<p><i>iereis</i></p>
			<p><i>ieren</i></p>
		</futuro>
		</subjuntivo>
	<imperativo>
		<imperativo-afirmativo>
			<p><i>e</i></p>
			<p><i>ga</i></p>
			<p><i>gamos</i></p>
			<p><i>id</i></p>
			<p><i>gan</i></p>
		</imperativo-afirmativo>
		<imperativo-non>
			<p><i>gas</i></p>
			<p><i>ga</i></p>
			<p><i>gamos</i></p>
			<p><i>gáis</i></p>
			<p><i>gan</i></p>
		</imperativo-non>
	</imperativo>
	<condicional>
		<condicional-present>
			<p><i>iría</i></p>
			<p><i>irías</i></p>
			<p><i>iría</i></p>
			<p><i>iríamos</i></p>
			<p><i>iríais</i></p>
			<p><i>irían</i></p>
		</condicional-present>
		</condicional>
	<infinitivo>
		<infinitivo-infinitivo>
			<p><i>ir</i></p>
			<p><i>ido</i></p>
		</infinitivo-infinitivo>
	</infinitivo>
	<gerundio>
		<gerundio-gerondio>
			<p><i>iendo</i></p>
			<p><i>ido</i></p>
		</gerundio-gerondio>
	</gerundio>
	<participo>
		<participo-participo>
			<p><i>ido</i></p>
		</participo-participo>
	</participo>
</template>

<template name="a:ullar">
	<indicativo>
		<presente>
			<p><i>úllo</i></p>
			<p><i>úllas</i></p>
			<p><i>úlla</i></p>
			<p><i>ullamos</i></p>
			<p><i>ulláis</i></p>
			<p><i>úllan</i></p>
		</presente>
		<pretérito-imperfecto>
			<p><i>ullaba</i></p>
			<p><i>ullabas</i></p>
			<p><i>ullaba</i></p>
			<p><i>ullábamos</i></p>
			<p><i>ullabais</i></p>
			<p><i>ullaban</i></p>
		</pretérito-imperfecto>
		<pretérito-perfecto-simple>
			<p><i>ullé</i></p>
			<p><i>ullaste</i></p>
			<p><i>ulló</i></p>
			<p><i>ullamos</i></p>
			<p><i>ullasteis</i></p>
			<p><i>ullaron</i></p>
		</pretérito-perfecto-simple>
		<futuro>
			<p><i>ullaré</i></p>
			<p><i>ullarás</i></p>
			<p><i>ullará</i></p>
			<p><i>ullaremos</i></p>
			<p><i>ullaréis</i></p>
			<p><i>ullarán</i></p>
		</futuro>
		</indicativo>
	<subjuntivo>
		<presente>
			<p><i>úlle</i></p>
			<p><i>úlles</i></p>
			<p><i>úlle</i></p>
			<p><i>ullemos</i></p>
			<p><i>ulléis</i></p>
			<p><i>úllen</i></p>
		</presente>
		<pretérito-imperfecto-1>
			<p><i>ullara</i></p>
			<p><i>ullaras</i></p>
			<p><i>ullara</i></p>
			<p><i>ulláramos</i></p>
			<p><i>ullarais</i></p>
			<p><i>ullaran</i></p>
		</pretérito-imperfecto-1>
		<pretérito-imperfecto-2>
			<p><i>ullase</i></p>
			<p><i>ullases</i></p>
			<p><i>ullase</i></p>
			<p><i>ullásemos</i></p>
			<p><i>ullaseis</i></p>
			<p><i>ullasen</i></p>
		</pretérito-imperfecto-2>
		<futuro>
			<p><i>ullare</i></p>
			<p><i>ullares</i></p>
			<p><i>ullare</i></p>
			<p><i>ulláremos</i></p>
			<p><i>ullareis</i></p>
			<p><i>ullaren</i></p>
		</futuro>
		</subjuntivo>
	<imperativo>
		<imperativo-afirmativo>
			<p><i>úlla</i></p>
			<p><i>úlle</i></p>
			<p><i>ullemos</i></p>
			<p><i>ullad</i></p>
			<p><i>úllen</i></p>
		</imperativo-afirmativo>
		<imperativo-non>
			<p><i>úlles</i></p>
			<p><i>úlle</i></p>
			<p><i>ullemos</i></p>
			<p><i>ulléis</i></p>
			<p><i>úllen</i></p>
		</imperativo-non>
	</imperativo>
	<condicional>
		<condicional-present>
			<p><i>ullaría</i></p>
			<p><i>ullarías</i></p>
			<p><i>ullaría</i></p>
			<p><i>ullaríamos</i></p>
			<p><i>ullaríais</i></p>
			<p><i>ullarían</i></p>
		</condicional-present>
		</condicional>
	<infinitivo>
		<infinitivo-infinitivo>
			<p><i>ullar</i></p>
			<p><i>ullado</i></p>
		</infinitivo-infinitivo>
	</infinitivo>
	<gerundio>
		<gerundio-gerondio>
			<p><i>ullando</i></p>
			<p><i>ullado</i></p>
		</gerundio-gerondio>
	</gerundio>
	<participo>
		<participo-participo>
			<p><i>ullado</i></p>
		</participo-participo>
	</participo>
</template>

<template name="averg:onzar">
	<indicativo>
		<presente>
			<p><i>üenzo</i></p>
			<p><i>üenzas</i></p>
			<p><i>üenza</i></p>
			<p><i>onzamos</i></p>
			<p><i>onzáis</i></p>
			<p><i>üenzan</i></p>
		</presente>
		<pretérito-imperfecto>
			<p><i>onzaba</i></p>
			<p><i>onzabas</i></p>
			<p><i>onzaba</i></p>
			<p><i>onzábamos</i></p>
			<p><i>onzabais</i></p>
			<p><i>onzaban</i></p>
		</pretérito-imperfecto>
		<pretérito-perfecto-simple>
			<p><i>oncé</i></p>
			<p><i>onzaste</i></p>
			<p><i>onzó</i></p>
			<p><i>onzamos</i></p>
			<p><i>onzasteis</i></p>
			<p><i>onzaron</i></p>
		</pretérito-perfecto-simple>
		<futuro>
			<p><i>onzaré</i></p>
			<p><i>onzarás</i></p>
			<p><i>onzará</i></p>
			<p><i>onzaremos</i></p>
			<p><i>onzaréis</i></p>
			<p><i>onzarán</i></p>
		</futuro>
		</indicativo>
	<subjuntivo>
		<presente>
			<p><i>üence</i></p>
			<p><i>üences</i></p>
			<p><i>üence</i></p>
			<p><i>oncemos</i></p>
			<p><i>oncéis</i></p>
			<p><i>üencen</i></p>
		</presente>
		<pretérito-imperfecto-1>
			<p><i>onzara</i></p>
			<p><i>onzaras</i></p>
			<p><i>onzara</i></p>
			<p><i>onzáramos</i></p>
			<p><i>onzarais</i></p>
			<p><i>onzaran</i></p>
		</pretérito-imperfecto-1>
		<pretérito-imperfecto-2>
			<p><i>onzase</i></p>
			<p><i>onzases</i></p>
			<p><i>onzase</i></p>
			<p><i>onzásemos</i></p>
			<p><i>onzaseis</i></p>
			<p><i>onzasen</i></p>
		</pretérito-imperfecto-2>
		<futuro>
			<p><i>onzare</i></p>
			<p><i>onzares</i></p>
			<p><i>onzare</i></p>
			<p><i>onzáremos</i></p>
			<p><i>onzareis</i></p>
			<p><i>onzaren</i></p>
		</futuro>
		</subjuntivo>
	<imperativo>
		<imperativo-afirmativo>
			<p><i>üenza</i></p>
			<p><i>üence</i></p>
			<p><i>oncemos</i></p>
			<p><i>onzad</i></p>
			<p><i>üencen</i></p>
		</imperativo-afirmativo>
		<imperativo-non>
			<p><i>üences</i></p>
			<p><i>üence</i></p>
			<p><i>oncemos</i></p>
			<p><i>oncéis</i></p>
			<p><i>üencen</i></p>
		</imperativo-non>
	</imperativo>
	<condicional>
		<condicional-present>
			<p><i>onzaría</i></p>
			<p><i>onzarías</i></p>
			<p><i>onzaría</i></p>
			<p><i>onzaríamos</i></p>
			<p><i>onzaríais</i></p>
			<p><i>onzarían</i></p>
		</condicional-present>
		</condicional>
	<infinitivo>
		<infinitivo-infinitivo>
			<p><i>onzar</i></p>
			<p><i>onzado</i></p>
		</infinitivo-infinitivo>
	</infinitivo>
	<gerundio>
		<gerundio-gerondio>
			<p><i>onzando</i></p>
			<p><i>onzado</i></p>
		</gerundio-gerondio>
	</gerundio>
	<participo>
		<participo-participo>
			<p><i>onzado</i></p>
		</participo-participo>
	</participo>
</template>

<template name="averig:uar">
	<indicativo>
		<presente>
			<p><i>uo</i></p>
			<p><i>uas</i></p>
			<p><i>ua</i></p>
			<p><i>uamos</i></p>
			<p><i>uáis</i></p>
			<p><i>uan</i></p>
		</presente>
		<pretérito-imperfecto>
			<p><i>uaba</i></p>
			<p><i>uabas</i></p>
			<p><i>uaba</i></p>
			<p><i>uábamos</i></p>
			<p><i>uabais</i></p>
			<p><i>uaban</i></p>
		</pretérito-imperfecto>
		<pretérito-perfecto-simple>
			<p><i>üé</i></p>
			<p><i>uaste</i></p>
			<p><i>uó</i></p>
			<p><i>uamos</i></p>
			<p><i>uasteis</i></p>
			<p><i>uaron</i></p>
		</pretérito-perfecto-simple>
		<futuro>
			<p><i>uaré</i></p>
			<p><i>uarás</i></p>
			<p><i>uará</i></p>
			<p><i>uaremos</i></p>
			<p><i>uaréis</i></p>
			<p><i>uarán</i></p>
		</futuro>
		</indicativo>
	<subjuntivo>
		<presente>
			<p><i>üe</i></p>
			<p><i>ües</i></p>
			<p><i>üe</i></p>
			<p><i>üemos</i></p>
			<p><i>üéis</i></p>
			<p><i>üen</i></p>
		</presente>
		<pretérito-imperfecto-1>
			<p><i>uara</i></p>
			<p><i>uaras</i></p>
			<p><i>uara</i></p>
			<p><i>uáramos</i></p>
			<p><i>uarais</i></p>
			<p><i>uaran</i></p>
		</pretérito-imperfecto-1>
		<pretérito-imperfecto-2>
			<p><i>uase</i></p>
			<p><i>uases</i></p>
			<p><i>uase</i></p>
			<p><i>uásemos</i></p>
			<p><i>uaseis</i></p>
			<p><i>uasen</i></p>
		</pretérito-imperfecto-2>
		<futuro>
			<p><i>uare</i></p>
			<p><i>uares</i></p>
			<p><i>uare</i></p>
			<p><i>uáremos</i></p>
			<p><i>uareis</i></p>
			<p><i>uaren</i></p>
		</futuro>
		</subjuntivo>
	<imperativo>
		<imperativo-afirmativo>
			<p><i>ua</i></p>
			<p><i>üe</i></p>
			<p><i>üemos</i></p>
			<p><i>uad</i></p>
			<p><i>üen</i></p>
		</imperativo-afirmativo>
		<imperativo-non>
			<p><i>ües</i></p>
			<p><i>üe</i></p>
			<p><i>üemos</i></p>
			<p><i>üéis</i></p>
			<p><i>üen</i></p>
		</imperativo-non>
	</imperativo>
	<condicional>
		<condicional-present>
			<p><i>uaría</i></p>
			<p><i>uarías</i></p>
			<p><i>uaría</i></p>
			<p><i>uaríamos</i></p>
			<p><i>uaríais</i></p>
			<p><i>uarían</i></p>
		</condicional-present>
		</condicional>
	<infinitivo>
		<infinitivo-infinitivo>
			<p><i>uar</i></p>
			<p><i>uado</i></p>
		</infinitivo-infinitivo>
	</infinitivo>
	<gerundio>
		<gerundio-gerondio>
			<p><i>uando</i></p>
			<p><i>uado</i></p>
		</gerundio-gerondio>
	</gerundio>
	<participo>
		<participo-participo>
			<p><i>uado</i></p>
		</participo-participo>
	</participo>
</template>

<template name=":caber">
	<indicativo>
		<presente>
			<p><i>quepo</i></p>
			<p><i>cabes</i></p>
			<p><i>cabe</i></p>
			<p><i>cabemos</i></p>
			<p><i>cabéis</i></p>
			<p><i>caben</i></p>
		</presente>
		<pretérito-imperfecto>
			<p><i>cabía</i></p>
			<p><i>cabías</i></p>
			<p><i>cabía</i></p>
			<p><i>cabíamos</i></p>
			<p><i>cabíais</i></p>
			<p><i>cabían</i></p>
		</pretérito-imperfecto>
		<pretérito-perfecto-simple>
			<p><i>cupe</i></p>
			<p><i>cupiste</i></p>
			<p><i>cupo</i></p>
			<p><i>cupimos</i></p>
			<p><i>cupisteis</i></p>
			<p><i>cupieron</i></p>
		</pretérito-perfecto-simple>
		<futuro>
			<p><i>cabré</i></p>
			<p><i>cabrás</i></p>
			<p><i>cabrá</i></p>
			<p><i>cabremos</i></p>
			<p><i>cabréis</i></p>
			<p><i>cabrán</i></p>
		</futuro>
		</indicativo>
	<subjuntivo>
		<presente>
			<p><i>quepa</i></p>
			<p><i>quepas</i></p>
			<p><i>quepa</i></p>
			<p><i>quepamos</i></p>
			<p><i>quepáis</i></p>
			<p><i>quepan</i></p>
		</presente>
		<pretérito-imperfecto-1>
			<p><i>cupiera</i></p>
			<p><i>cupieras</i></p>
			<p><i>cupiera</i></p>
			<p><i>cupiéramos</i></p>
			<p><i>cupierais</i></p>
			<p><i>cupieran</i></p>
		</pretérito-imperfecto-1>
		<pretérito-imperfecto-2>
			<p><i>cupiese</i></p>
			<p><i>cupieses</i></p>
			<p><i>cupiese</i></p>
			<p><i>cupiésemos</i></p>
			<p><i>cupieseis</i></p>
			<p><i>cupiesen</i></p>
		</pretérito-imperfecto-2>
		<futuro>
			<p><i>cupiere</i></p>
			<p><i>cupieres</i></p>
			<p><i>cupiere</i></p>
			<p><i>cupiéremos</i></p>
			<p><i>cupiereis</i></p>
			<p><i>cupieren</i></p>
		</futuro>
		</subjuntivo>
	<imperativo>
		<imperativo-afirmativo>
			<p><i>cabe</i></p>
			<p><i>quepa</i></p>
			<p><i>quepamos</i></p>
			<p><i>cabed</i></p>
			<p><i>quepan</i></p>
		</imperativo-afirmativo>
		<imperativo-non>
			<p><i>quepas</i></p>
			<p><i>quepa</i></p>
			<p><i>quepamos</i></p>
			<p><i>quepáis</i></p>
			<p><i>quepan</i></p>
		</imperativo-non>
	</imperativo>
	<condicional>
		<condicional-present>
			<p><i>cabría</i></p>
			<p><i>cabrías</i></p>
			<p><i>cabría</i></p>
			<p><i>cabríamos</i></p>
			<p><i>cabríais</i></p>
			<p><i>cabrían</i></p>
		</condicional-present>
		</condicional>
	<infinitivo>
		<infinitivo-infinitivo>
			<p><i>caber</i></p>
			<p><i>cabido</i></p>
		</infinitivo-infinitivo>
	</infinitivo>
	<gerundio>
		<gerundio-gerondio>
			<p><i>cabiendo</i></p>
			<p><i>cabido</i></p>
		</gerundio-gerondio>
	</gerundio>
	<participo>
		<participo-participo>
			<p><i>cabido</i></p>
		</participo-participo>
	</participo>
</template>

<template name="ca:er">